### ISSUE TITLE
Got error when running. bruteforce 

### ISSUE THREAD

**Issue by vdvcoder** [LordNeoStark/tugarecon#3]
python3 tugarecon.py -d google.com -b --full
        
             ______                  ____                      
            /_  __/_  ______ _____ _/ __ \___  _________  ____ 
             / / / / / / __ `/ __ `/ /_/ / _ \/ ___/ __ \/ __ \                
            / / / /_/ / /_/ / /_/ / _, _/  __/ /__/ /_/ / / / /               
           /_/  \__,_/\__, /\__,_/_/ |_|\___/\___/\____/_/ /_/  V: 0.45b               
                     /____/                                    

                        # Coded By LordNeoStark #
    
TugaRecon, tribute to Portuguese explorers reminding glorious past of this country

[+] DNS queries...

**************************************************************

google.com. 5 IN A 172.217.168.238 

google.com. 21 IN AAAA 2a00:1450:400e:807::200e 

google.com. 595 IN MX 50 alt4.aspmx.l.google.com.
google.com. 595 IN MX 30 alt2.aspmx.l.google.com.
google.com. 595 IN MX 20 alt1.aspmx.l.google.com.
google.com. 595 IN MX 40 alt3.aspmx.l.google.com.
google.com. 595 IN MX 10 aspmx.l.google.com. 

google.com. 29266 IN NS ns1.google.com.
google.com. 29266 IN NS ns4.google.com.
google.com. 29266 IN NS ns3.google.com.
google.com. 29266 IN NS ns2.google.com. 

google.com. 300 IN TXT "globalsign-smime-dv=CDYX+XFHUw2wml6/Gb8+59BsH31KzUr6c1l2BPvqKX8="
google.com. 300 IN TXT "docusign=1b0a6754-49b1-4db5-8540-d2c12664b289"
google.com. 300 IN TXT "docusign=05958488-4752-4ef2-95eb-aa7ba8a3bd0e"
google.com. 300 IN TXT "facebook-domain-verification=22rm551cu4k0ab0bxsw536tlds4h95"
google.com. 300 IN TXT "v=spf1 include:_spf.google.com ~all" 

google.com. 36 IN SOA ns1.google.com. dns-admin.google.com. 297077745 900 900 1800 60 

Traceback (most recent call last):
  File "tugarecon.py", line 177, in <module>
    menu()
  File "tugarecon.py", line 173, in menu
    main(target, output, savemap, enum, threads, bruteforce, args)
  File "tugarecon.py", line 116, in main
    d = TugaBruteScan(target, options=args)
  File "/home/olivier/tools/tugarecon/tugascan.py", line 40, in __init__
    self._dns_queries = _dns_queries(target)
  File "/home/olivier/tools/tugarecon/lib/bscan.py", line 13, in _dns_queries
    answer = dns.resolver.query(target, qtype, raise_on_no_answer=False)
  File "/home/olivier/.local/lib/python3.6/site-packages/dns/resolver.py", line 1102, in query
    lifetime)
  File "/home/olivier/.local/lib/python3.6/site-packages/dns/resolver.py", line 898, in query
    raise NoNameservers(request=request, errors=errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query google.com. IN MINFO: Server 127.0.0.53 UDP port 53 answered NOTIMP
^[[A^CException ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

**Comment by LordNeoStark** [comment]
Please, try install the last version...

`    dnspython
    threading
    queue
    re
    os
    time
    sys
    webbrowser
    urllib3`

![Screenshot from 2020-02-26 21-58-37](https://user-images.githubusercontent.com/39160972/75392319-b1adcf80-58e3-11ea-81ab-976148383628.png)

**Comment by LordNeoStark** [comment]
dnspython = version 1.16.0 :)
